### ISSUE TITLE
config_data.cc:41 failed to save config to stream.

### ISSUE THREAD

**Issue by CallMeR** [rime/plum#13]
rime.ibus.***.****.log.ERROR.20180723-174540.2230:
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0723 17:45:40.169962  2233 config_data.cc:41] failed to save config to stream.

rime.ibus.***.****.log.WARNING.20180723-174540.2230:
W0723 17:54:52.346007  2849 config_data.cc:62] nonexistent config file '/home/***/.config/ibus/rime/build/ibus_rime.yaml'.
E0723 17:54:52.745831  2852 config_data.cc:41] failed to save config to stream.
W0723 17:54:52.746665  2852 config_data.cc:62] nonexistent config file '/home/*****/.config/ibus/rime/build/ibus_rime.yaml'.

**Comment by lotem** [comment]
Fixed via https://github.com/rime/librime/commit/68c8a344739c70978a0de0fc47e0f13988c0340e
