### ISSUE TITLE
Incorrect user directory

### ISSUE THREAD

**Issue by chromezh** [rime/plum#2]
Hello, I am using weasel 0.11.1 and when I run `Rime package installer` it gives the following information:

```
Working directory: E:\Programs\Rime\weasel-0.11.1
Package installer directory: E:\Programs\Rime\weasel-0.11.1\
Download cache directory: C:\Users\lenovo\AppData\Local\Temp
Rime user directory: C:\Users\lenovo\AppData\Roaming\Rime
```

However, my `Rime user directory` should be `F:\RimeDict`, not `C:\Users\lenovo\AppData\Roaming\Rime
`.

I was afraid that the program will download schemata into incorrect directory, so I did not continue.

Thanks in advance!

**Comment by lotem** [comment]
You are right.
Great. You read the output carefully.
For now, the script cannot automatically read your customized user directory location from Windows registry.
You can manually edit the variable `rime_dir` in `rime-install-config.bat`. More details:
https://github.com/rime/plum#use-git-for-incremental-updates-optional
