### ISSUE TITLE
如果想把一個方案也加到這裡面，是否可以? 需要如何處理?

### ISSUE THREAD

**Issue by philipposkhos** [rime/plum#26]
Hi

目前這裡面的默認速成方案，是按字頻選字和自動組詞的，但很多使用速成的用戶習慣於固定排序選字，所以我整理了一個符合速成使用習慣排字(按微軟速成)的方案，請問是否可以添加至此?

當初 windows 8 推出時，也是用 新速成(按字頻選字) 來取代舊有固定排序的速成，但之後因為速成使用者的反饋，最終添加回了傳統排字的版本，所以我覺得多提供一種傳統排字的版本，可以令使用 rime 的速成用戶更為方便。

如果可以，我需要如何做?

https://github.com/philipposkhos/rime-ms-quick

**Comment by sgalal** [comment]
我個人認為如果沒有修改詞庫，只是改動方案的話，可以直接將新的方案和原方案並置於原來的倉庫。

或者待到第三方方案列表完成後，將這個倉庫加入第三方方案列表，便於索引。

**Comment by philipposkhos** [comment]
詞庫是指 .dict.yaml 嗎? 如果是這個，這個是按微軟速成(包含香港增補字符集字元)的順序另外錄入的

**Comment by sgalal** [comment]
那我個人覺得可以待到第三方方案列表解決以後，加入第三方方案列表中，不一定要加入官方列表

**Comment by philipposkhos** [comment]
明白，謝謝
