### ISSUE TITLE
Userdata path

### ISSUE THREAD

**Issue by jack980517** [rime/plum#28]
https://github.com/rime/plum/blob/master/rime-install.bat#L13
为了便携，我将userdata目录自行指定到了另外的位置。然而rime-install.bat并不读注册表，weaselsetup.exe也并不设定rime_dir这个环境变量。这就造成我改的userdata目录并没有被rime-install.bat使用。请修正，谢谢。

**Comment by lotem** [comment]
同 https://github.com/rime/plum/issues/2
