### ISSUE TITLE
倉頡碼錯誤

### ISSUE THREAD

**Issue by DiksonH** [rime/plum#32]
(不清楚放在這對不對...)
"黃"字的倉頡五代碼應該是"廿一田金", 但現在碼表是"廿一中金", 好像是三代的碼

**Comment by lotem** [comment]
三代和五代倉頡的字根和涉及這個字的拆分、取碼規則沒有差別。題中所舉的不同編碼可能用於描述不同字形。
https://www.zdic.net/hans/%E9%BB%83
如圖所示「黃」字「田」形上方與「一」之間有一出頭的豎劃，按照五代的取碼規則，應取一、二、三、末碼即「廿一中金」。
