### ISSUE TITLE
[wontfix]当系统中有 WSL (Windows Subsystem for Linux) 时会使用 Linux 的 bash

### ISSUE THREAD

**Issue by amorphobia** [rime/plum#35]
这样会导致以下两个问题：

1. plum bootstrap 下载的 shell 脚本的换行被保存为 CRLF (\r\n), WSL 的 bash 不能识别
2. 手动将 shell 脚本的换行改为 LF (\n) 后，输入方案被安装到 WSL 的 `~/.config/ibus/rime` 里，而不是 Windows 的 `%APPDATA%\Rime`

**Comment by lotem** [comment]
WSL的問題先不處理了。配方管理器有待用新的技術重新實現。

**Comment by lotem** [comment]
第二個問題已經在[這裏](https://github.com/rime/weasel/commit/371e08e4c799beef15ec93b461b17125c77f166b)解決。
