### ISSUE TITLE
Help, I don't know how to install double-pinyin

### ISSUE THREAD

**Issue by p2635** [rime/plum#39]
OS: Kubuntu 20.04

I already have RIME installed, the default installed schemas work fine but I don't have double-pinyin.

What I've tried:
- `sudo apt-get install librime-data-double-pinyin` and then restarted ibus, the option is not there
- `rime-install --select :extra` and then selected double-pinyin and then restarted ibus, the option is not there

I can see that the double-pinyin schemas are in /home/user/.config/ibus/rime/

**Comment by lotem** [comment]
请参考：
https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE

**Comment by p2635** [comment]
thanks @lotem, I put the **patch:** part on the top:

```
# default.custom.yaml

patch:
  schema_list:
    - schema: double_pinyin_flypy

__patch:
# Rx: custom:set:config=default,key=installed_from,value=rime-cantonese {
  - patch/+:
      installed_from: rime-cantonese
# }
# Rx: custom:add:schema=jyut6ping3 {
  - patch/+:
      schema_list/+/+:
        - schema: jyut6ping3
# }

```

It works now but all the defaults have disappeared:
![image](https://user-images.githubusercontent.com/4522927/94605729-6c92b700-0291-11eb-92a8-cb296b242d92.png)

It's pretty much solved but I must be doing something that's not quite right.

**Comment by p2635** [comment]
I give up, it's too hard. I will just use ibus-pinyin

**Comment by p2635** [comment]
I found the issue, I had to edit default.yaml. I have a question, sorry if it's the wrong place to ask. What is the point of 'sudo apt install librime-data-double-pinyin'? It does nothing. I had to still use plum + edit default.yaml myself.

**Comment by lotem** [comment]
This is how to *append* items to the list:

```yaml
# default.custom.yaml

patch:
  schema_list/+:
    - schema: double_pinyin_flypy
```

To install schema files, either use plum/rime-install or use the Linux package manager. Either wil do, you don't need both.

**Comment by p2635** [comment]
Oh! @lotem I will try deleting the files added by plum in that case and see what happens, thanks for the tip
