### ISSUE TITLE
linux 上fcitx不生成default.custom.yaml

### ISSUE THREAD

**Issue by spphinslove** [rime/plum#40]
使用 rime_frontend=fcitx-rime5 bash rime-install（希望在readme 添加一下说明）安装了其他输入法，没有在.local/share/fcitx5/rime/下生成default.custom.yaml，手动创建添加
patch:
  schema_list:
    - {schema: pinyin_simp}
    - {schema: wubixinshiji_pinyin}
后才好了。

**Comment by lotem** [comment]
`default.custom.yaml` 这个文件是用户根据需要自己创建的，只写用户修改的配置项。

**Comment by lotem** [comment]
哦。说的是安装的输入方案没有启用吧。
另有一个参数化配方用来启用输入方案：
https://github.com/rime/rime-custom#%E6%B7%BB%E5%8A%A0%E8%BC%B8%E5%85%A5%E6%96%B9%E6%A1%88%E5%88%B0%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE

分成两项操作，因为
安装了未必要启用（启用输入方案涉及修改用户配置，比如安装到共享文件夹而非用户文件夹、安装大量方案后用户有选择地启用个别方案）；
一个配方包可以包含多个输入方案（如 https://github.com/rime/rime-double-pinyin），往往需要用户自己决定启用哪个。
