### ISSUE TITLE
Inclusion of Japanese input methods

### ISSUE THREAD

**Issue by BrandonKMLee** [rime/plum#46]
For RIME's Japanese input:
- https://github.com/gkovacs/rime-japanese

If iBus is included using https://github.com/rime/home/wiki/RimeWithIBus :
- https://wiki.archlinux.org/index.php/Input_Japanese_using_uim#Mozc
- https://wiki.archlinux.org/index.php/Input_Japanese_using_uim#Anthy

**Comment by Iey4iej3** [comment]
At the moment, you could simply run the command `rime-install gkovacs/rime-japanese` as described in [Advanced usage](https://github.com/rime/plum/blob/master/README.md).

**Comment by BrandonKMLee** [comment]
@Iey4iej3 hope that Rime-Japanese can be mainlined into main options
