### ISSUE TITLE
present-packages.conf: No such file or directory

### ISSUE THREAD

**Issue by nigolarer** [rime/plum#48]
when i tried to install as  Readme leaded, i got the following error:
```
Installing for Rime frontend: rime/squirrel
./scripts/resolver.sh: line 89: ./present-packages.conf: No such file or directory
```

after looked around the root path folder the most familiar file is `preset-packages.conf`, thus i run command 
```
mv preset-packages.conf present-packages.conf
```
 idk which one has typo tho.

**Comment by lotem** [comment]
it's `preset`.
