### ISSUE TITLE
増加简化和原字一起可选的输出选项

### ISSUE THREAD

**Issue by kentsin** [rime/plum#50]
有些工作不单要打传统字或简字， 而是所有字都有用

现在要在打码之前选输出简字或传统字而这样会打断工作。如果有一选项可以将简化字和原字都在选字表中可选则可免打断工作

**Comment by lotem** [comment]
選擇不轉換，就是顯示所有選項的。
例如「朙月拼音」方案的詞典包含所有簡繁漢字，不轉換時都顯示在選項表裏。開啓簡化字模式則只顯示簡化字。
