### ISSUE TITLE
bash: rime-install: No such file or directory

### ISSUE THREAD

**Issue by oodzchen** [rime/plum#54]
我用的是 macOS 12.2.1，安装完 Squirrel 之后，在 `Terminal.app` 中执行了 `curl -fsSL https://git.io/rime-install | bash`，然后运行 `bash rime-install`，结果提示如下：
> bash: rime-install: No such file or directory

请问是我哪里操作错误吗

**Comment by lotem** [comment]
说明没写清楚。
题主描述的情况下，可以把命令改成 `bash plum/rime-install`
