### ISSUE TITLE
github 被墙，curl 会 timeout

### ISSUE THREAD

**Issue by tristone13th** [rime/plum#55]
最近 Github 越来越难访问了，有时候会因为网络问题安装错误，用了 proxifier 加 clash 代理的方式也会报 git.io 的证书问题，有没有什么解决办法？

**Comment by lotem** [comment]
最新代码已经不再访问 git.io

**Comment by tristone13th** [comment]
> 最新代码已经不再访问 git.io

小狼毫好像还是在用 git.io 的版本

**Comment by lotem** [comment]
只对[该修改](https://github.com/rime/plum/commit/9588b5af3c1c0256df4f4d3b3eb508274a95dc42)之后发布的有效。没办法回到三年前去修改当时发布的软件包。

> > 最新代码已经不再访问 git.io
> 
> 小狼毫好像还是在用 git.io 的版本
