### ISSUE TITLE
mac无法安装plum(could not create work tree dir 'plum': Read-only file system)

### ISSUE THREAD

**Issue by kc-li** [rime/plum#60]
我通过最新的rime-Cantonese安装了rime ([link](https://github.com/rime/rime-cantonese/releases))，现在还想安装IPA和中古汉语拼音，根据界面说明都需要用东风破rime-install来安装。我尝试了以下命令，

curl -fsSL https://git.io/rime-install | bash
curl -fsSL https://raw.githubusercontent.com/rime/plum/master/rime-install | bash
但是都提示：
could not create work tree dir 'plum': Read-only file system

请问应该怎么处理呢？

我的设备是Mac M1, Ventura 13.2.1

**Comment by lotem** [comment]
需要對工作目錄有寫權限。嘗試先輸入命令：

```sh
cd $HOME
```

**Comment by kc-li** [comment]
非常感谢！解决了我的问题！
