### ISSUE TITLE
请问怎么向plum贡献新的输入方案？

### ISSUE THREAD

**Issue by Gs-Linguashop** [rime/plum#75]

**Comment by ksqsf** [comment]
https://github.com/rime/rppi

plum本身没有所谓的「贡献方案」一说。你可以把它理解成是一个方案管理器，而不是一个方案仓库。

**Comment by Gs-Linguashop** [comment]
请问别人可以在plum上查到我制作的方案吗？如果不可以，怎么让别人在plum上查到我的方案呢？

谢谢

**Comment by ksqsf** [comment]
不能，plum没有查询方案的功能。

**Comment by lotem** [comment]
現在沒有。希望將來能有個統一的資源站。我早早註冊了域名，但是開發滯後了。

下一步先把工具升級。畢竟腳本工具用家不滿意。
https://github.com/lotem/rime-make
https://github.com/lotem/rime-cli
