### ISSUE TITLE
五笔无法安装啊

### ISSUE THREAD

**Issue by zacksleo** [rime/plum#9]
```
➜  ~curl -fsSL https://git.io/rime-install | bash
....
Installing: terra_pinyin.dict.yaml
Installing: terra_pinyin.schema.yaml
Updated 17 files from 7 packages in '/Users/zacksleo/Library/Rime'

➜  ~ bash rime-install wubi pinyin-simp
bash: rime-install: No such file or directory

```

**Comment by lotem** [comment]
After `curl -fsSL https://git.io/rime-install | bash`, first change to the `plum` directory, you'll find `rime-install` there:

```sh
cd plum
bash rime-install wubi pinyin-simp
```

or 

```sh
bash plum/rime-install wubi pinyin-simp
```

**Comment by msongz** [comment]
: command not foundline 2:
'lum/rime-install: line 53: syntax error near unexpected token `do
'lum/rime-install: line 53: `for target in "${targets[@]}"; do

follow your step ```bash plum/rime-install wubi pinyin-simp```
and get the above error
